### PR TITLE
Allow building with `deepseq-1.5.*` (GHC 9.8)

### PR DESCRIPTION
**Pull request by RyanGlScott**

### CODE REVIEW

**Review by goldfirere — APPROVED** [review]

**Comment by RyanGlScott** [comment]
Thanks, @goldfirere!

Would you be able to merge and release these changes? (I don't have the ability to do so myself.)

**Comment by goldfirere** [comment]
Happy to, in theory, but would like CI working first. Evidently that will take a little work though. Hopefully later this week.

**Comment by RyanGlScott** [comment]
Ah, the CI failure is easy enough to explain: you're running the CI jobs on an old version of Ubuntu that GitHub Actions no longer supports. Since there are no longer any CI runners with that version of Ubuntu, GitHub Actions gets stuck trying to assign jobs to runners.

This is easy enough to fix by regenerating your `haskell-ci.yml` file with a more recent version of `haskell-ci` that targets a newer Ubuntu. I'll open a separate PR for that.

**Comment by RyanGlScott** [comment]
Thanks for giving me push access, @goldfirere! I don't have the ability to apply a Hackage revision, however. Could you also grant me Hackage permissions?

**Comment by RyanGlScott** [comment]
A gentle ping on this, @goldfirere. Can you grant me Hackage permissions for the `units` library?

**Pull request merged**
